include:
  - ./airflow/docker-compose.yml

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio:RELEASE.2023-11-06T22-26-08Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  rabbitmq-to-minio:
    build:
      context: .
      dockerfile: ./src/Dockerfile.minio
    depends_on:
      - rabbitmq
      - minio

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tpNoSQL

  rabbitmq-to-mongodb:
    build:
      context: .
      dockerfile: ./src/Dockerfile.mongodb
    depends_on:
      - rabbitmq
      - mongodb