FROM python:3.8

WORKDIR /app

# Copier le script Python
COPY ./src/2_rabbit_to_db.py /app/


# Installer les dépendances
RUN pip3 install pika pymongo


# Définir la commande à exécuter au lancement
ENTRYPOINT ["python", "2_rabbit_to_db.py"]


